variables:
  MINICONDA_VERSION: 4.5.4
  CONDA_VERSION: 4.5.11

jobs:
- template: ci/job.unix-like.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    MINICONDA_OS: Linux

- template: ci/job.unix-like.yml
  parameters:
    name: Mac
    vmImage: macos-10.13
    MINICONDA_OS: MacOSX

- template: ci/job.win.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
  
