pool:
  vmImage: Ubuntu 16.04

variables:
  MINICONDA_VERSION: 4.5.4
  MINICONDA_MD5: a946ea1d0c4a642ddf0c3a26a18bb16d
  CONDA_VERSION: 4.5.11

steps:
- script: |-
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh \
    && echo "${MINICONDA_MD5} *Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" | md5sum -c - \
    && bash Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -fbp $HOME/miniconda3 \
    && $HOME/miniconda3/bin/conda install -yn base conda==$CONDA_VERSION
  displayName: Install Miniconda

- script: $HOME/miniconda3/bin/conda env update -n base --file environment.yml
  displayName: Update Environment

- script: source $HOME/miniconda3/bin/activate && python -m scripts.lint
  displayName: Lint

- script: source $HOME/miniconda3/bin/activate && python -m scripts.build
  displayName: Build

- script: source $HOME/miniconda3/bin/activate && python -m scripts.test
  displayName: Test
