variables:
  MINICONDA_VERSION: 4.5.4
  CONDA_VERSION: 4.5.11

jobs:
- template: ci/job.unix-like.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/job.unix-like.yml
  parameters:
    name: MacOSX
    vmImage: macos-10.13

- template: ci/job.win.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
