name: _robots_from_jupyter

channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
  - https://conda.anaconda.org/conda-forge

dependencies:
  - conda
  - conda-build
  - conda-verify
  - constructor
  - geckodriver
  - python >=3.7,<3.8
  - robotframework
  - robotframework-seleniumlibrary
