name: _robots_from_jupyter

channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
  - https://conda.anaconda.org/conda-forge

dependencies:
  - conda
  - conda-build >=3.15,<3.16
  - conda-verify
  - constructor
  - geckodriver
  - python >=3.6,<3.7
  - robotframework
  - robotframework-seleniumlibrary
