{% set name = "lunr" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43143c7f857af9147b3e2621ec273c6b783b8eda65e8c2d5dcd4973c43b46254

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python
  run:
    - future
    - python
    - six
test:
  imports:
    - lunr

about:
  home: https://github.com/yeraydiazdiaz/lunr.py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python implementation of Lunr.js
  doc_url: https://lunr.readthedocs.io
