{% set name = "robotframework-lint" %}
{% set version = "0.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a71c54f342af0a988243c34cb887895e1256a9a45050692c33e0306f5420bf6c

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - rflint = rflint.__main__:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - robotframework

test:
  imports:
    - rflint
  commands:
    - rflint --help

about:
  home: https://github.com/boakley/robotframework-lint
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Linter for robot framework plain text files'
