package:
  name: {% set name = "itkwidgets" %}{{ name }}
  version: {% set version = "0.15.0" %}{{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 479ef5128de8bbf25a45b98dc25e7ae492ba0927991ee2253daacd0908526970
  patches:
    - setup.py.nojs.patch

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: True  # [py<34]

requirements:
  host:
    - python
    - pip
  run:
    - itk >=4.13.1
    - ipydatawidgets >=3.2.0
    - ipywidgets >=7.4.0
    - ipympl
    - numpy
    - scipy
    - six
    - zstandard

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/apache-2.0.txt
  summary: Interactive Jupyter widgets to visualize images in 2D and 3D
