{% set name = "robotkernel" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98289a72b5bd075428b2535b094b30a5c294c790ec36452870d7711ea01bbab2
  patches:
    - setup.cfg.patch

build:
  number: 0
  skip: true  # [py<36]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - "{{ PYTHON }} -m robotkernel.install"

requirements:
  build:
    - patch
  host:
    - ipython
    - jupyter_client
    - pip
    - python
  run:
    - docutils
    - ipykernel
    - lunr
    - pillow
    - pygments
    - python
    - robotframework

test:
  imports:
    - robotkernel
  commands:
    - jupyter kernelspec list

about:
  home: https://github.com/datakurre/robotkernel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Robot Framework IPython kernel for Jupyter Notebook and JupyterLab
