{% set name = "robotkernel" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af15b97beb2d21219c0c9d0443fd4f7b628f2f12d55967d6cbebe0f1c20a7d2c
  patches:
    - setup.cfg.patch

build:
  number: 0
  skip: true  # [py<36]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    - cd {{ RECIPE_DIR }} && {{ PYTHON }} install.py

requirements:
  build:
    - patch
  host:
    - pip
    - python
  run:
    - docutils
    - ipykernel
    - lunr
    - pillow
    - pygments
    - python
    - robotframework

test:
  imports:
    - robotkernel
  commands:
    - jupyter kernelspec list

about:
  home: https://github.com/datakurre/robotkernel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Robot Framework IPython kernel for Jupyter Notebook and JupyterLab
