parameters:
  name: Windows
  vmImage: vs2017-win2016

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}

    steps:
      - template: steps.conda.yml

      - script: >
          pip install git+https://github.com/conda/constructor --ignore-installed --no-deps
        displayName: Until 2.3.0 comes out, use constructor@master for size_in_bytes fix

      - template: steps.common.yml
        parameters:
          name: ${{ parameters.name }}
