parameters:
  name: Windows
  vmImage: vs2017-win2016
  MINICONDA_VERSION: 4.5.4
  MINICONDA_MD5: 1c73051ccd997770288275ee6474b423
  CONDA_VERSION: 4.5.11

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - displayName: Install Miniconda
    script: >
      powershell -command "& {Invoke-WebRequest https://repo.anaconda.com/miniconda/Miniconda3-%MINICONDA_VERSION%-Windows-x86_64.exe}"
      && start /wait "" Miniconda3-%MINICONDA_VERSION%-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=c:\mc3
      && c:\mc3\Scripts\conda install -yn base conda==%CONDA_VERSION%

  - displayName: Update Environment
    script: >
      c:\mc3\Scripts\conda env update -n base --file environment.yml
      && conda info --json
      && conda list

  - displayName: Lint
    script: >
      c:\mc3\Scripts\activate
      && python -m scripts.lint

  - displayName: Build Conda Packages
    script: >
      c:\mc3\Scripts\activate
      && python -m scripts.build conda
        lunr
        robotframework
        robotframework-lint
        robotframework-seleniumlibrary
        robotkernel
        robotlab
      && xcopy -r _artifacts\conda-bld %BUILD_ARTIFACTSTAGINGDIRECTORY%\conda-bld /E

  - displayName: Build Constructor
    script: >
      c:\mc3\Scripts\activate
      && python -m scripts.build constructor
      && xcopy _artifacts\constructor %BUILD_ARTIFACTSTAGINGDIRECTORY%\constructor /E

  - displayName: Test
    script: >
      c:\mc3\Scripts\activate
      && xpython -m scripts.test

  - condition: always()
    script: >
      xcopy _artifacts\test_output %BUILD_ARTIFACTSTAGINGDIRECTORY%\test_output /E
