parameters:
  name: Windows
  vmImage: vs2017-win2016
  CONDA_VERSION: 4.5.11

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: CondaEnvironment@1

  - script: >
      conda env update -n base --file environment.yml
      && conda info --json
      && conda list
    displayName: Update Environment

  - script: python -m scripts.lint
    displayName: Lint

  - script: >
      python -m scripts.build conda
        lunr
        robotframework
        robotframework-lint
        robotframework-seleniumlibrary
        robotkernel
        robotlab
      && xcopy -r _artifacts\conda-bld %BUILD_ARTIFACTSTAGINGDIRECTORY%\conda-bld /E
    displayName: Build Conda Packages

  - script: >
      python -m scripts.build constructor
      && xcopy _artifacts\constructor %BUILD_ARTIFACTSTAGINGDIRECTORY%\constructor /E
    displayName: Build Constructor

  - script: python -m scripts.test
    displayName: Test

  - script: xcopy _artifacts\test_output %BUILD_ARTIFACTSTAGINGDIRECTORY%\test_output /E
    condition: always()
