parameters:
  name: Windows
  vmImage: vs2017-win2016

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: CondaEnvironment@1
    inputs:
      installOptions: -c conda-forge
      packageSpecs: >
        conda>=4.5.11,<4.6
        conda-build>=3.15,<3.16
        conda-verify
        constructor
        geckodriver
        python>=3.6,<3.7
        python-chromedriver-binary
        robotframework
        robotframework-seleniumlibrary

  - script: >
      python -m scripts.build conda
        lunr
        robotframework
        robotframework-lint
        robotframework-seleniumlibrary
        robotkernel
        robotlab
      && xcopy -r _artifacts\conda-bld %BUILD_ARTIFACTSTAGINGDIRECTORY%\conda-bld /E
    displayName: Build Conda Packages

  - script: >
      python -m scripts.build constructor
      && xcopy _artifacts\constructor %BUILD_ARTIFACTSTAGINGDIRECTORY%\constructor /E
    displayName: Build Constructor

  - script: python -m scripts.test
    displayName: Test

  - script: xcopy _artifacts\test_output %BUILD_ARTIFACTSTAGINGDIRECTORY%\test_output /E
    condition: always()
