package:
  name: {% set name = "testflo" %}{{ name }}
  version: {% set version = "1.3.1" %}{{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d20274dce2bfb1bc09539c04489fd03533a50b90ac1af2b89b9f4d41134d5821

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - testflo=testflo.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - coverage

test:
  imports:
    - testflo
  commands:
    - testflo --help

about:
  home: https://github.com/OpenMDAO/testflo
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A simple python testing framework that can run unit tests under MPI (or not).
